name: Java CI/CD workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
          name: jar-artifact
          path: target/
    - name: Docker build
      run: |
        docker build . -t yassinesayadi/pe-backend:latest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push yassinesayadi/pe-backend:latest
        

